float32 gyroscope_x
float32 gyroscope_y
float32 gyroscope_z

float32 accelerometer_x
float32 accelerometer_y
float32 accelerometer_z

float32 magnetometer_x
float32 magnetometer_y
float32 magnetometer_z

float32 roll_speed
float32 pitch_speed
float32 heading_speed

float32 roll
float32 pitch
float32 heading

float32 q1
float32 q2
float32 q3
float32 q4

float32 temperature
float32 pressure
float32 pressure_temp
int32 timestamp
